### ISSUE TITLE
Missing AndroidManifest.xml and plugin_name.aar on `npm pack`

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nativescript-plugin-seed#114]
### Which platform(s) does your issue occur on?
- Android

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.2.0
- Cross-platform modules: 5.2.0
- Runtime(s): 5.2.0

### Please, tell us how to recreate the issue in as much detail as possible. 
1) Clone the seed.
2) `cd nativescript-yourplugin/src`
3) `npm run postclone`
4) `npm pack`
5) The whole `platforms/android` is missing in the generated tgz.

### Additional Context
The manifest is not included because it is npm ignored from `.npmignore`, while the `aar` is not built because we do not force `tns plugin build` on `npm pack` anymore (because of [this change](https://github.com/NativeScript/nativescript-plugin-seed/commit/070b7ffaef85d7fe82209d7bb8371e1e71db5ba0#diff-59f51de4945d3a9a80a254062862997bL28)).

**Comment by zbranzov** [comment]
@DimitarTachev  The issue was that the npm prepack command was triggered by unknown to us event when running jobs in travisCI. Thus, the build was trying to build android aar on mac where no android build setup was available. In order to revert that change I will suggest the following change:
- Improve the script https://github.com/NativeScript/nativescript-plugin-seed/blob/master/src/scripts/build-native.js so it runs the command only in terms of available android build setup. Is that ok?

**Comment by zbranzov** [comment]
The issue was caused by a package-lock.json file which triggered the prepack script on 'npm i'. Therefore, we will revert the prepack command and stop generating lock file in the demo folder
