### ISSUE TITLE
Adding stripe to include.gradle breaks build

### ISSUE THREAD

**Issue by RobertGardner** [NativeScript/nativescript-plugin-seed#88]
I am working on a plugin that uses Stripe. It works well for iOS but I'm having trouble getting it to work for Android. To reproduce I started with the nativescript-plugin-seed following the Build Plugin instructions to create nativescript-version-number. This works and I can successfully run and debug it in the Android Studio emulator.

I then add `compile 'com.stripe:stripe-android:8.0.0'` to `src/platforms/android/include.gradle` in the `dependencies` section. Now `npm run demo.android` fails to build, with the following error:
```
 ~/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.0.aar/bf7a4c30edcd7fbace87de38a1ae35a7/res/values-v26/values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.
```
(Plus several other resources and style attributes that it can't find.)
I tried `npm run clean` and deleting `.gradle/caches` but still get the same error.

### 
- Building on Mac OSX for Android. Installed Android Studio and using that emulator.
- CLI: 4.1.2
- Cross-platform modules: tns-core-modules is 4.1.1
- Runtime(s): tns-android: 4.1.3
- Plugin(s): unmodified from this seed

### Please, tell us how to recreate the issue in as much detail as possible.
1. Follow the instructions at https://docs.nativescript.org/plugins/building-plugins and create a local copy of nativescript-version-number.
2. Make just one change: to `include.gradle` add the following to the dependencies block:
```
    compile 'com.stripe:stripe-android:8.0.0'
```
3. `npm run plugin.tscwatch` (success); `npm run demo.android` (fails)

**Comment by DimitarTodorov** [comment]
Hi @RobertGardner ,

We've tried the steps you described but we can't reproduce the issue. We've tested it and the `npm run demo.android` command works fine and the app run on device. 

Though, searching in the web for similar cases, when there is an error relevant to resource android:attr/colorError not found, one of the reason is compiling with older version of android SDK. The attribute named "android:attr/colorError" is referenced by the appcompat library at API 26 and above. 
https://github.com/NativeScript/nativescript-cli/issues/3552 Here is an issue which describes a similar case, where updating the complieSdkVersion to 26 fixes it.

**Comment by RobertGardner** [comment]
Thank you. That gave me enough information that I can now proceed.

I am new to Android development, so I'm not sure everything I did was necessary, but I had to uninstall my avd running Lollipop and install one running Oreo. The demo now compiles and runs.

I want to target my app to Lollipop because it's so much more widely used. This experience leaves me worried, but I have a lot to do before I have to face that problem!

(By the way, the NativeScript instructions for setting up and getting a working installation using Android Studio are confusing, difficult to follow, and incomplete, especially for someone new to Android.)
