### ISSUE TITLE
Reference Error: xxx is not defined

### ISSUE THREAD

**Issue by AshleyCao** [NativeScript/nativescript-plugin-seed#94]
### Make sure to check the demo app(s) for sample usage 
Yes
### Make sure to check the existing issues in this repository 
Yes
### If the demo apps cannot help and there is no issue for your problem, tell us about it
JS: Reference Error: xxx (java package name) not defined.
### Which platform(s) does your issue occur on?
- Android 5.1
- emulator
### Please, provide the following version numbers that your issue occurs with:
- CLI: 4.2.3
- Cross-platform modules: 4.2.0
- Runtime(s): 4.0.0
- Plugin(s):     
    "nativescript-theme-core": "^1.0.4",
    "nativescript-unit-test-runner": "^0.3.4",
    "nativescript-bluetoothspp": "file:../src",
    "tns-core-modules": "^4.2.0"
### Please, tell us how to recreate the issue in as much detail as possible. 
Follow "Building Plugins" to get demo work -->Generate .aar via android studio. -->Generate typing files by following android-dts-generator. -->Add typing files and change reference.s.ts  --> build--> JS: Reference Error: xxx(java package name) not defined. --> remove android folder in platform and rebuild (or try commands to clean plugin and demo files) --> same error
### Is there any code involved? 
Here is the repository : https://github.com/AshleyCao/nativescrip-bluetooth-spp

**Comment by lini** [comment]
Hi,
I looked in the repository that you posted and I think that the error you see is because the class you are trying to use (`pfdfoods.foodservice.ashleycao.bluetoothspp.BluetoothSPP`) is not implemented anywhere. You have created the typings for it so inside the code editor it will look OK and the TypeScript compiler will not complain, but the native code that runs on the device is not present. You should either reference your library (if already built) in the  `/src/platforms/android/include.gradle` file, or if you are writing the code yourself, you should compile it in the `/src/platforms/android/nativescript_bluetoothspp.aar` library. 

For an example of such an implementation (source code compiled into aar) you can review the code of the [nativescript-push-notifications](https://github.com/NativeScript/push-plugin) plugin. For an example of a plugin where a 3rd party library is referenced, you can review the [nativescript-background-http](https://github.com/NativeScript/nativescript-background-http) plugin.

**Comment by AshleyCao** [comment]
Hi @lini, Thanks for your answer. 
What I did is to copy the .aar file I generate from Android Studio to /src/platforms/android and now problem sloved.
